### ISSUE TITLE
Null property value for 'distro.codename' on bean class 'class com.google.gson.internal.LinkedTreeMap'

### ISSUE THREAD

**Issue by ahonor** [latamdevs/rundeck-puppetenterprise-nodes-plugin#6] opened 2015-10-29 21:00 UTC
2015-10-29 15:51:51,984 [qtp598987586-63] ERROR com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource - [ResourceModelSource: 2.puppet-enterprise (PuppetDB Nodes Plugin), project: XXXYY-testing] 
org.apache.commons.beanutils.NestedNullException: Null property value for 'distro.codename' on bean class 'class com.google.gson.internal.LinkedTreeMap'
	at org.apache.commons.beanutils.PropertyUtilsBean.getNestedProperty(PropertyUtilsBean.java:793)
	at org.apache.commons.beanutils.PropertyUtilsBean.getProperty(PropertyUtilsBean.java:884)
	at com.rundeck.plugin.resources.puppetdb.Mapper.getPuppetNodeProperty(Mapper.java:178)
	at com.rundeck.plugin.resources.puppetdb.Mapper.getPuppetNodeProperty(Mapper.java:152)
	at com.rundeck.plugin.resources.puppetdb.Mapper.assembleMap(Mapper.java:123)
	at com.rundeck.plugin.resources.puppetdb.Mapper.apply(Mapper.java:79)
	at com.rundeck.plugin.resources.puppetdb.Mapper$1.apply(Mapper.java:243)
	at com.rundeck.plugin.resources.puppetdb.Mapper$1.apply(Mapper.java:240)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:268)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:373)
	at com.rundeck.plugin.resources.puppetdb.ResourceModelFactory$1.getNodes(ResourceModelFactory.java:114)
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:45)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:88)
	at com.dtolabs.rundeck.core.common.FrameworkProject.getNodeSet(FrameworkProject.java:380)
	at com.dtolabs.rundeck.core.common.IRundeckProject$getNodeSet$3.call(Unknown Source)
	at rundeck.controllers.FrameworkController.nodeSummaryAjax(FrameworkController.groovy:466)
	at rundeck.controllers.FrameworkController.nodeSummaryAjax(FrameworkController.groovy)

**Comment by miguelantonio** [comment] 2015-10-29 21:25
@dustinak I think this is your same error

**Comment by dustinak** [comment] 2015-10-29 21:31
I believe so, yes. That was when I reworked the mappings and removed the distro.codename as it appears we are not populating that in our puppetdb.

**Comment by dustinak** [comment] 2015-10-29 21:33
It should be noted that when I used a mappings file that did not include that fact, it did not error and still I never saw the nodes in the project from within Rundeck.

**Comment by miguelantonio** [comment] 2015-10-29 21:39
Ok then I'll create another issue for that

**Comment by robertopaez** [comment] 2015-10-30 08:51
@dustinak could you showme the mapping file that was causing the issue?

**Comment by miguelantonio** [comment] 2015-10-30 14:21
@ahonor we are still looking into this, for now a work around is to remove the fact "distro.codename" from the mapping file, can you try again to see if the no-nodes issue (#7) happens?

**Comment by ahonor** [comment] 2015-10-30 15:15
@miguelantonio ok will give it a try without the "thirdAttribute". Perhaps we should remove it from the default mapping if it is not common.
Alternatively, maybe the plugin can just ignore generating an attribute when the fact does not exist.

**Comment by miguelantonio** [comment] 2015-10-30 15:41
@ahonor weird thing is, we cannot reproduce the error even with made up attributes, null or even non existent ones don't produce null values on the attribute map, but we are on it!

**Comment by ahonor** [comment] 2015-10-30 17:15
After removing that thirdAttribute, the error is:

015-10-30 11:09:54,854 [qtp598987586-63] WARN  com.rundeck.plugin.resources.puppetdb.client.DefaultPuppetAPI - getClasses(devpupamq1l.usaa.com) ended with status code: 404
2015-10-30 11:09:55,065 [qtp598987586-63] WARN  com.rundeck.plugin.resources.puppetdb.client.DefaultPuppetAPI - getClasses(devpupm1l.xxx.com) ended with status code: 404
2015-10-30 11:09:55,281 [qtp598987586-63] WARN  com.rundeck.plugin.resources.puppetdb.client.DefaultPuppetAPI - getClasses(devpupca1l.xxx.com) ended with status code: 404
2015-10-30 11:09:55,451 [qtp598987586-63] WARN  com.rundeck.plugin.resources.puppetdb.client.DefaultPuppetAPI - getClasses(devpupm2l.xxx.com) ended with status code: 404
2015-10-30 11:09:55,617 [qtp598987586-63] WARN  com.rundeck.plugin.resources.puppetdb.client.DefaultPuppetAPI - getClasses(devpupdbs1l.xxx.com) ended with status code: 404
2015-10-30 11:09:55,794 [qtp598987586-63] WARN  com.rundeck.plugin.resources.puppetdb.client.DefaultPuppetAPI - getClasses(devpuppet1l.xxx.com) ended with status code: 404
2015-10-30 11:09:56,001 [qtp598987586-63] WARN  com.rundeck.plugin.resources.puppetdb.client.DefaultPuppetAPI - getClasses(devpupdb1l.xxx.com) ended with status code: 404

**Comment by miguelantonio** [comment] 2015-10-30 17:21
@ahonor oh! these seem to be from getting the classes get, the API URL is not found apparently, what is the puppet enterprise version?

and also, what is the behavior in rundeck?

**Comment by miguelantonio** [comment] 2015-10-30 19:36
@dustinak I just published a fix for this problem, can you confirm it?

**Comment by miguelantonio** [comment] 2015-10-30 19:36
please? :)

**Closed** 2015-11-03 16:19 UTC
Labels: bug
